# Generated by Django 2.1.3 on 2018-12-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0002_auto_20181208_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media/profile_images'),
        ),
    ]
