# Generated by Django 2.1 on 2018-12-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0003_auto_20181204_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby',
            field=models.CharField(max_length=100),
        ),
    ]
