# Generated by Django 2.1.3 on 2018-12-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0004_userprofilemodel_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='likes',
            field=models.ManyToManyField(blank=True, to='FriendZoneApp.UserProfileModel'),
        ),
    ]
