# Generated by Django 2.1.3 on 2018-12-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0005_userprofilemodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='likes',
        ),
    ]
