# Generated by Django 2.1 on 2018-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0006_auto_20181205_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='hobby',
            field=models.ManyToManyField(blank=True, to='FriendZoneApp.Hobby'),
        ),
    ]
