# Generated by Django 2.1.3 on 2018-12-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0006_remove_userprofilemodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
