# Generated by Django 2.1 on 2018-12-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0008_auto_20181205_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby',
            field=models.CharField(blank=True, choices=[('Gaming', 'Gaming'), ('Sports', 'Sports'), ('Reading', 'Reading'), ('Hiking', 'Hiking'), ('Cycling', 'Cycling'), ('Photography', 'Photography'), ('Modelling', 'Modelling')], max_length=20),
        ),
    ]
