# Generated by Django 2.1.3 on 2018-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendZoneApp', '0008_auto_20181216_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='profileBio',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
